export const FOOD_BY_CATEGORY = {
  meat: [
    "Chicken Adobo",
    "Chicken Adobo Garlic",
    "Chicken Adobo Soy-Vinegar",
    "Chicken Inasal",
    "Chicken Afritada",
    "Chicken Pastel",
    "Pork Adobo",
    "Pork Adobo Dry",
    "Pork Adobo Pineapple",
    "Pork Sinigang",
    "Pork Menudo",
    "Pork Kare-Kare",
    "Lechon",
    "Pork Barbecue",
    "Longganisa",
    "Sisig",
    "Pork Embutido",
    "Beef Tapa",
    "Beef Mechado",
    "Beef Caldereta",
    "Beef Nilaga",
    "Beef Pares",
    "Beef Pares Dry",
    "Pork Binagoongan",
    "Paksiw na Pata",
    "Bistek Tagalog",
    "Crispy Pata",
    "Adobong Baboy sa Puti",
    "Inihaw na Baboy",
    "Inihaw na Manok",
    "Tinolang Manok",
    "Menudo",
    "Afritada",
    "Kaldereta",
    "Pochero",
    "Nilagang Baboy",
    "Nilagang Baka",
    "Dinakdakan",
    "Pinangat na Baboy",
    "Lechon Kawali",
    "Tokwa’t Baboy",
    "Pritong Baboy",
    "Pritong Manok",
    "Chicken Barbecue",
    "Pork Barbecue Skewers",
    "Beef BBQ",
    "Pork BBQ Skewers",
    "Jollibee Chickenjoy",
    "Jollibee Burger Steak",
    "Mang Inasal Chicken Inasal",
    "Mang Inasal Pork BBQ",
    "McDonald's Chicken McDo",
    "Chowking Fried Chicken",
    "Chowking Sweet and Sour Pork",
    "Chowking Peking Duck",
    "Adobong Manok sa Gata",
    "Chicken Binakol",
    "Pork Sinampalukang Baboy",
    "Beef Kaldereta with Potatoes",
    "Beef Morcon",
    "Pork Embutido with Egg",
    "Sisig with Egg",
    "Chicken Tocino",
    "Pork Tocino",
    "Beef Tapa Breakfast",
    "Lechon Paksiw",
    "Crispy Pata with Sauce",
    "Chicken BBQ with Liempo",
    "Pork BBQ Liempo",
    "Inihaw na Liempo",
    "Inihaw na Manok with Sauce",
    "Chicken Afritada with Potatoes",
    "Beef Afritada",
    "Pork Afritada",
    "Beef Pares Stew",
    "Beef Pares with Sauce",
    "Pork Caldereta",
    "Chicken Caldereta",
    "Pork Nilaga",
    "Beef Nilaga with Vegetables",
    "Pork Menudo with Carrots",
    "Chicken Menudo",
    "Beef Mechado with Tomato Sauce",
    "Beef Tapa with Rice",
    "Pork Barbecue with Atchara",
    "Chicken BBQ with Rice",
    "Inihaw na Manok sa Uling",
    "Inihaw na Baboy sa Uling",
    "Chicken Barbecue with Marinade",
    "Lechon Baboy",
    "Lechon Manok",
    "Crispy Fried Chicken",
    "Roast Pork Belly",
    "Roast Chicken",
    "Bistek Tagalog with Onions",
    "Adobong Baboy sa Bawang",
    "Pininyahang Manok",
    "Chicken Ala King",
    "Pork Sisig",
    "Beef Salpicao",
    "Chicken Salpicao",
    "Bistek Baka",
    "Lechon Kawali Crispy",
    "Tocino Breakfast",
    "Chicken Nuggets Filipino Style"
  ],
  fish: [
    "Bangus",
    "Bangus Relleno",
    "Bangus Daing",
    "Tilapia",
    "Pinaputok na Tilapia",
    "Tuna",
    "Grilled Tuna",
    "Sinigang na Tuna",
    "Pusit",
    "Adobong Pusit",
    "Grilled Pusit",
    "Stuffed Pusit",
    "Hito",
    "Sinigang na Hito",
    "Fried Hito",
    "Crab",
    "Ginataang Alimasag",
    "Crab with Coconut Milk",
    "Shrimp",
    "Sardines",
    "Lapu-Lapu",
    "Dilis",
    "Alimasag",
    "Tamban",
    "Galunggong",
    "Halaan",
    "Inihaw na Isda",
    "Kinilaw na Isda",
    "Sinigang na Hipon",
    "Ginataang Hipon",
    "Pinaputok na Tilapia sa Prito",
    "Daing na Bangus",
    "Daing na Tilapia",
    "Grilled Lapu-Lapu",
    "Escabeche na Isda",
    "Paksiw na Isda",
    "Pinangat na Isda",
    "Inihaw na Pusit",
    "Shrimp Adobo",
    "Shrimp Butter Garlic",
    "Crab Butter Garlic",
    "Crab with Coconut Cream",
    "Grilled Hito",
    "Fried Tilapia",
    "Sinigang na Bangus",
    "Sinigang na Tilapia",
    "Inihaw na Sardines",
    "Fried Galunggong",
    "Stuffed Lapu-Lapu",
    "Pinaputok na Tilapia with Vegetables",
    "Daing na Pompano",
    "Tinolang Isda",
    "Halabos na Hipon",
    "Shrimp Sinigang",
    "Ginataang Alimango",
    "Crab Sinigang",
    "Inihaw na Alimango",
    "Adobong Alimango",
    "Tinolang Hipon",
    "Pusit Stuffed with Vegetables",
    "Grilled Tuna Belly",
    "Grilled Pompano",
    "Kinilaw na Tuna",
    "Kinilaw na Bangus",
    "Shrimp Calamari",
    "Fried Pusit Rings",
    "Pinangat na Hipon",
    "Inihaw na Halaan",
    "Inihaw na Dilis",
    "Crispy Fried Tilapia",
    "Grilled Galunggong",
    "Sinigang na Alimango",
    "Ginataang Hipon at Sitaw",
    "Shrimp in Garlic Sauce",
    "Crab Curry",
    "Pusit in Ink Sauce",
    "Daing na Bangus Breakfast",
    "Sautéed Bangus Belly",
    "Baked Lapu-Lapu",
    "Fried Hito with Soy Sauce",
    "Shrimp Tempura Filipino Style",
    "Grilled Hito with Sauce",
    "Pompano Escabeche",
    "Inihaw na Hipon",
    "Pusit ala Pobre",
    "Grilled Alimango",
    "Sinigang na Pusit",
    "Ginataang Pusit",
    "Shrimp Sinigang with Vegetables",
    "Steamed Crab Filipino Style",
    "Adobong Hipon",
    "Daing na Dilis",
    "Fried Shrimp",
    "Tilapia Sinigang",
    "Grilled Sardines",
    "Grilled Tamban",
    "Baked Bangus"
  ],
  plant: [
    "Kangkong",
    "Adobong Kangkong",
    "Ginisang Kangkong",
    "Stir-fried Kangkong",
    "Ampalaya",
    "Ginisang Ampalaya",
    "Ampalaya con Carne",
    "Pinakbet Ampalaya",
    "Upo",
    "Ginisang Upo",
    "Upo Soup",
    "Steamed Upo",
    "Sitaw",
    "Ginisang Sitaw",
    "Pinakbet Sitaw",
    "Talong",
    "Tortang Talong",
    "Grilled Talong",
    "Ginisang Talong",
    "Pechay",
    "Camote Leaves",
    "Malunggay",
    "Gabi",
    "Labanos",
    "Kalabasa",
    "Patola",
    "Baguio Beans",
    "Singkamas",
    "Sayote",
    "Pipino",
    "Kintsay",
    "Alugbati",
    "Kamote",
    "Tomato",
    "Onion",
    "Garlic",
    "Ginger",
    "Ampalaya with Egg",
    "Talong Omelette",
    "Ginisang Baguio Beans",
    "Ginisang Kalabasa",
    "Pinakbet Mix",
    "Ginisang Sayote",
    "Pechay with Garlic",
    "Ginisang Alugbati",
    "Ginisang Camote Leaves",
    "Steamed Malunggay",
    "Ginisang Patola",
    "Ginisang Labanos",
    "Ginisang Singkamas",
    "Ginisang Sitaw with Tofu",
    "Ampalaya Guisado",
    "Ginisang Upo with Shrimp",
    "Kangkong Adobo",
    "Talong with Tomato Sauce",
    "Pinakbet with Shrimp Paste",
    "Ginisang Talong at Kamatis",
    "Ginataang Kalabasa",
    "Ginataang Sitaw at Kalabasa",
    "Ginisang Talong at Ampalaya",
    "Ginisang Pechay with Garlic",
    "Ginisang Upo with Ground Pork",
    "Pinakbet with Meat",
    "Ginisang Kamote Tops",
    "Ginisang Malunggay at Hipon",
    "Ginisang Alugbati at Tofu",
    "Ginisang Patola at Hipon",
    "Ginisang Baguio Beans with Meat",
    "Ginisang Kalabasa with Pork",
    "Ginisang Sitaw with Tofu",
    "Steamed Kangkong",
    "Pinakbet Without Meat",
    "Ginisang Sayote with Egg",
    "Ginisang Labanos with Shrimp",
    "Ginisang Kamote with Coconut Milk",
    "Ginisang Ampalaya with Egg",
    "Talong with Ground Pork",
    "Ginisang Baguio Beans and Pork",
    "Ginisang Upo at Hipon",
    "Ginisang Patola with Tofu",
    "Ginisang Malunggay with Pork",
    "Ginisang Kintsay",
    "Ginisang Singkamas at Hipon",
    "Ginisang Camote Tops with Egg",
    "Ginisang Pechay at Hipon",
    "Ginisang Talong at Hipon",
    "Ginisang Sitaw at Kalabasa with Pork",
    "Ginisang Kalabasa with Shrimp",
    "Ginisang Kamote with Tofu",
    "Ginisang Talong at Tofu",
    "Ginisang Ampalaya at Hipon",
    "Ginisang Pechay at Tofu",
    "Ginisang Kangkong with Egg",
    "Ginisang Malunggay at Tofu",
    "Ginisang Patola at Pork",
    "Ginisang Baguio Beans at Hipon",
    "Ginisang Upo at Tofu",
    "Ginisang Sitaw at Hipon"
  ],
  mixed: [
    "Sinigang",
    "Pork Sinigang",
    "Beef Sinigang",
    "Fish Sinigang",
    "Shrimp Sinigang",
    "Tinola",
    "Chicken Tinola",
    "Ginger Tinola",
    "Tinola with Malunggay",
    "Pinakbet",
    "Laing",
    "Bicol Express",
    "Chopsuey",
    "Pancit Canton",
    "Pancit Bihon",
    "Pancit Malabon",
    "Pancit Palabok",
    "Pancit Luglug",
    "Pancit Habhab",
    "Bulalo",
    "Dinengdeng",
    "Arroz Caldo",
    "Goto",
    "Kansi",
    "Batchoy",
    "Menudo",
    "Afritada",
    "Kaldereta",
    "Chicken Sotanghon Soup",
    "Beef Nilaga",
    "Pochero",
    "Pinaputok na Tilapia",
    "Paksiw na Isda",
    "Escabeche",
    "Kilawin",
    "Adobong Pusit",
    "Ginataang Sitaw at Kalabasa",
    "Ginataang Langka",
    "Kare-Kare",
    "Pochero Soup",
    "Nilagang Baboy",
    "Nilagang Baka",
    "Bulanglang",
    "Kadyos Baboy Langka",
    "Sarsa ng Baka",
    "Dinakdakan",
    "Pinangat",
    "Inabraw",
    "Tinumpak",
    "Jollibee Jolly Spaghetti",
    "Jollibee Palabok Fiesta",
    "McDonald's McSpaghetti",
    "Mang Inasal Halo-Halo",
    "Chowking Lauriat Meal",
    "Chowking Beef Macaroni Soup",
    "Chowking Siomai",
    "Sinigang na Baboy at Kangkong",
    "Sinigang na Baka at Labong",
    "Sinigang na Hipon at Kangkong",
    "Tinolang Manok at Sayote",
    "Tinolang Manok at Malunggay",
    "Pinakbet with Bagoong",
    "Bicol Express with Pork",
    "Chopsuey with Tofu",
    "Bulalo with Corn",
    "Dinengdeng with Eggplant",
    "Arroz Caldo with Chicken",
    "Goto with Tofu",
    "Batchoy with Pork",
    "Menudo with Potato",
    "Afritada with Chicken",
    "Kaldereta with Beef",
    "Chicken Sotanghon with Vegetables",
    "Beef Nilaga with Sayote",
    "Pochero with Pork and Banana",
    "Pinaputok na Tilapia with Vegetables",
    "Paksiw na Isda with Vegetables",
    "Escabeche with Tilapia",
    "Kilawin na Tuna",
    "Adobong Pusit at Gulay",
    "Ginataang Sitaw at Kalabasa with Meat",
    "Ginataang Langka at Hipon",
    "Kare-Kare with Bagoong",
    "Pochero Soup with Chicken",
    "Nilagang Baboy with Vegetables",
    "Nilagang Baka with Corn",
    "Bulanglang with Tofu",
    "Kadyos Baboy Langka Soup",
    "Sarsa ng Baka with Rice",
    "Dinakdakan with Egg",
    "Pinangat na Baboy at Malunggay",
    "Inabraw with Eggplant",
    "Tinumpak with Vegetables",
    "Jolly Spaghetti with Hotdog",
    "Palabok Fiesta with Tofu",
    "McSpaghetti with Cheese",
    "Halo-Halo with Leche Flan",
    "Chowking Lauriat with Fried Chicken",
    "Beef Macaroni Soup with Vegetables",
    "Chowking Siomai with Sauce"
  ],
  dairy: [
    "Leche Flan",
    "Maja Blanca",
    "Ube Halaya",
    "Buko Pandan",
    "Mango Float",
    "Yema Cake",
    "Ube Cake",
    "Buko Pie",
    "Polvoron",
    "Cascaron",
    "Ensaymada",
    "Ice Cream Filipino Flavors",
    "Milk-based Champorado",
    "Yema",
    "Leche de Ube",
    "Pastillas de Leche",
    "Crema de Fruta",
    "Queso de Bola Desserts",
    "McDonald's McFloat",
    "McDonald's Sundae",
    "Jollibee Halo-Halo"
  ],
  skipped: ["skipped"]
} as const;

export type FoodCategory = keyof typeof FOOD_BY_CATEGORY;
