export const FOOD_BY_CATEGORY = {
  meat: [
    "Chicken Adobo",
    "Chicken Adobo Garlic",
    "Chicken Adobo Soy-Vinegar",
    "Chicken Inasal",
    "Chicken Afritada",
    "Chicken Pastel",
    "Pork Adobo",
    "Pork Adobo Dry",
    "Pork Adobo Pineapple",
    "Pork Sinigang",
    "Pork Menudo",
    "Pork Kare-Kare",
    "Lechon",
    "Pork Barbecue",
    "Longganisa",
    "Sisig",
    "Pork Embutido",
    "Beef Tapa",
    "Beef Mechado",
    "Beef Caldereta",
    "Beef Nilaga",
    "Beef Pares",
    "Beef Pares Dry",
    "Pork Binagoongan",
    "Paksiw na Pata",
    "Bistek Tagalog",
    "Crispy Pata",
    "Adobong Baboy sa Puti",
    "Inihaw na Baboy",
    "Inihaw na Manok",
    "Tinolang Manok",
    // Fast-food meat
    "Jollibee Chickenjoy",
    "Jollibee Burger Steak",
    "Mang Inasal Chicken Inasal",
    "Mang Inasal Pork BBQ",
    "McDonald's Chicken McDo",
    "Chowking Fried Chicken",
    "Chowking Sweet and Sour Pork",
    "Chowking Peking Duck"
  ],
  fish: [
    "Bangus",
    "Bangus Relleno",
    "Bangus Daing",
    "Tilapia",
    "Pinaputok na Tilapia",
    "Tuna",
    "Grilled Tuna",
    "Sinigang na Tuna",
    "Pusit",
    "Adobong Pusit",
    "Grilled Pusit",
    "Stuffed Pusit",
    "Hito",
    "Sinigang na Hito",
    "Fried Hito",
    "Crab",
    "Ginataang Alimasag",
    "Crab with Coconut Milk",
    "Shrimp",
    "Sardines",
    "Lapu-Lapu",
    "Dilis",
    "Alimasag",
    "Tamban",
    "Galunggong",
    "Halaan",
    "Inihaw na Isda",
    "Kinilaw na Isda",
    "Sinigang na Hipon",
    "Ginataang Hipon"
  ],
  plant: [
    "Kangkong",
    "Adobong Kangkong",
    "Ginisang Kangkong",
    "Stir-fried Kangkong",
    "Ampalaya",
    "Ginisang Ampalaya",
    "Ampalaya con Carne",
    "Pinakbet Ampalaya",
    "Upo",
    "Ginisang Upo",
    "Upo Soup",
    "Steamed Upo",
    "Sitaw",
    "Ginisang Sitaw",
    "Pinakbet Sitaw",
    "Talong",
    "Tortang Talong",
    "Grilled Talong",
    "Ginisang Talong",
    "Pechay",
    "Camote Leaves",
    "Malunggay",
    "Gabi",
    "Labanos",
    "Kalabasa",
    "Patola",
    "Baguio Beans",
    "Singkamas",
    "Sayote",
    "Pipino",
    "Kintsay",
    "Alugbati",
    "Kamote",
    "Tomato",
    "Onion",
    "Garlic",
    "Ginger"
  ],
  mixed: [
    "Sinigang",
    "Pork Sinigang",
    "Beef Sinigang",
    "Fish Sinigang",
    "Shrimp Sinigang",
    "Tinola",
    "Chicken Tinola",
    "Ginger Tinola",
    "Tinola with Malunggay",
    "Pinakbet",
    "Laing",
    "Bicol Express",
    "Chopsuey",
    "Pancit Canton",
    "Pancit Bihon",
    "Pancit Malabon",
    "Pancit Palabok",
    "Pancit Luglug",
    "Pancit Habhab",
    "Bulalo",
    "Dinengdeng",
    "Arroz Caldo",
    "Goto",
    "Kansi",
    "Batchoy",
    "Menudo",
    "Afritada",
    "Kaldereta",
    "Chicken Sotanghon Soup",
    "Beef Nilaga",
    "Pochero",
    "Pinaputok na Tilapia",
    "Paksiw na Isda",
    "Escabeche",
    "Kilawin",
    "Adobong Pusit",
    "Ginataang Sitaw at Kalabasa",
    "Ginataang Langka",
    "Kare-Kare",
    "Pochero Soup",
    "Nilagang Baboy",
    "Nilagang Baka",
    "Bulanglang",
    "Kadyos Baboy Langka",
    "Sarsa ng Baka",
    "Dinakdakan",
    "Pinangat",
    "Inabraw",
    "Tinumpak",
    // Fast-food mixed
    "Jollibee Jolly Spaghetti",
    "Jollibee Palabok Fiesta",
    "McDonald's McSpaghetti",
    "Mang Inasal Halo-Halo",
    "Chowking Lauriat Meal",
    "Chowking Beef Macaroni Soup",
    "Chowking Siomai"
  ],
  dairy: [
    "Leche Flan",
    "Maja Blanca",
    "Ube Halaya",
    "Buko Pandan",
    "Mango Float",
    "Yema Cake",
    "Ube Cake",
    "Buko Pie",
    "Polvoron",
    "Cascaron",
    "Ensaymada",
    "Ice Cream Filipino Flavors",
    "Milk-based Champorado",
    "Yema",
    "Leche de Ube",
    "Pastillas de Leche",
    "Crema de Fruta",
    "Queso de Bola Desserts",
    // Fast-food dairy
    "McDonald's McFloat",
    "McDonald's Sundae",
    "Jollibee Halo-Halo"
  ],
  skipped: ["skipped"]
} as const;

export type FoodCategory = keyof typeof FOOD_BY_CATEGORY;
